stages:
  - install
  - test
  - publish

include:
  - template: Jobs/Code-Intelligence.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

sast:
  stage: test

image: node:14-alpine

npm-install:
  stage: install
  rules:
    - if: $CI_COMMIT_TAG == null
  tags: ["ssd"]
  before_script:
    - apk add --update --no-cache python3 make gcc g++ && ln -sf python3 /usr/bin/python
  script:
    - yarn install --immutable
  cache: &global_npm_cache
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
      - .yarn/cache/
      - .yarn/install-state.gz
    policy: pull-push

test-test-jasmine:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  needs: ["npm-install"]
  script:
    - yarn test
  cache:
    <<: *global_npm_cache
    policy: pull

test-check-types-tsc:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  needs: ["npm-install"]
  script:
    - cp ./fixtures/config.api.json ./config.api.json
    - yarn test:ci:check-types
  cache:
    <<: *global_npm_cache
    policy: pull

npm-audit:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  needs: ["npm-install"]
  script:
    - npm audit &2>1 > npm-audit.log
    - cat npm-audit.log
  cache:
    <<: *global_npm_cache
    policy: pull
  artifacts:
    untracked: false
    expire_in: 1 year
    paths:
      - npm-audit.log

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - apk add jq curl
  script:
    - npm ci
    - cp ./fixtures/config.api.json ./config.api.json
    - yarn test
    - yarn build:esm2020
    - yarn build:cjs
    - yarn build:types
    - jq 'del(.devDependencies) | del(.scripts) | del(.jest)' package.json > build/package.json
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish ./build
    - NPM_VERSION=$(jq '.version' package.json -r)
    - >-
      NPM_TARBALL_URL=$(curl -H "JOB-TOKEN: ${CI_JOB_TOKEN}" ${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/@ssrg-tools%2Fbase | jq ".versions[\"$NPM_VERSION\"].dist.tarball" -r)
    - >-
      curl -X POST -H "JOB-TOKEN: ${CI_JOB_TOKEN}" -H "Content-Type: application/json" -d "{\"tag_name\": \"${CI_COMMIT_TAG}\", \"name\": \"${CI_COMMIT_TAG}\", \"body\": \"${CI_COMMIT_MESSAGE//[$'\t\r\n\"']}\", \"released_at\": \"${CI_COMMIT_TIMESTAMP}\", \"assets\": {\"links\": [{\"name\": \"$(basename "$NPM_TARBALL_URL")\", \"url\": \"${NPM_TARBALL_URL}\"}]}}" "${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/releases" -v --show-error --fail
