yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules

npmScopes:
  ssrg-tools:
    npmRegistryServer: "https://server.nellman.net/api/v4/packages/npm/"
  anhnyan:
    npmRegistryServer: "https://server.nellman.net/api/v4/packages/npm/"
