import {MigrationInterface, QueryRunner} from 'typeorm';

export class AddFiles1619500501289 implements MigrationInterface {
    name = 'AddFiles1619500501289';

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('ALTER TABLE `league_tracker` DROP FOREIGN KEY `FK_900818981d9eb49fd11fd70287c`');
        await queryRunner.query('ALTER TABLE `league_tracker` DROP FOREIGN KEY `FK_e0b3f9fcf35ff316a213c23d986`');
        await queryRunner.query('ALTER TABLE `song_beatmaps` DROP FOREIGN KEY `FK_c8d12ea5178e0709deb03433d82`');
        await queryRunner.query('ALTER TABLE `artists` DROP FOREIGN KEY `FK_2e2fda1dec4c9bc16704e9ff772`');
        await queryRunner.query('ALTER TABLE `users_logins` DROP FOREIGN KEY `FK_9afce9c631e9dd84f6f4c9b0bc9`');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` DROP FOREIGN KEY `FK_a2f2ebae5c9fcd5f2e6aac104ee`');
        await queryRunner.query('DROP INDEX `IDX_83862467ad0a3afd66f49af374` ON `song_beatmaps`');
        await queryRunner.query('DROP INDEX `IDX_c8d12ea5178e0709deb03433d8` ON `song_beatmaps`');
        await queryRunner.query('DROP INDEX `guid` ON `log_credits`');
        await queryRunner.query('DROP INDEX `IDX_e0a817b68f55d95f6721267439` ON `log_credits`');
        await queryRunner.query('DROP INDEX `IDX_c619094b8afd1e48d28b6ee9f7` ON `log_credits`');
        await queryRunner.query('DROP INDEX `IDX_58adef9aedebd662b88506583f` ON `log_diamonds`');
        await queryRunner.query('DROP INDEX `IDX_80a98de140c38f1ed48b486570` ON `log_diamonds`');
        await queryRunner.query('DROP INDEX `IDX_9402b99a15239b95309864535f` ON `log_diamonds_ads`');
        await queryRunner.query('DROP INDEX `IDX_994987d0bdbd132c351dc863a6` ON `log_diamonds_ads`');
        await queryRunner.query('DROP INDEX `IDX_8fcb2c96a7b43862c2a1a19c28` ON `log_diamonds_ads`');
        await queryRunner.query('DROP INDEX `IDX_5d02077d4941019273995220b5` ON `song_clear_cards`');
        await queryRunner.query('DROP INDEX `IDX_200c5368f75e3f5fab815d2ba2` ON `themes`');
        await queryRunner.query('DROP INDEX `IDX_7b72c0e6f5438539635fa2706d` ON `log_drops`');
        await queryRunner.query('DROP INDEX `IDX_cc926133c401ae5e4c6cb943ee` ON `log_drops`');
        await queryRunner.query('DROP INDEX `IDX_2081b465971c6e81d5447e0f65` ON `log_drops`');
        await queryRunner.query('DROP INDEX `IDX_dd0918407944553611bb3eb3dd` ON `user_credentials`');
        await queryRunner.query('DROP INDEX `IDX_a3ffb1c0c8416b9fc6f907b743` ON `users`');
        await queryRunner.query('DROP INDEX `IDX_fefab589657440640cfda575fd` ON `song_world_records`');
        await queryRunner.query('DROP INDEX `IDX_ab62eccd228dff0992fcb44f05` ON `songs`');
        await queryRunner.query('DROP INDEX `IDX_390b24af470bafbd41bd092b62` ON `song_clears_v2`');
        await queryRunner.query('DROP INDEX `IDX_9be7492417d7ba450d31b0a8a2` ON `song_clears_v2`');
        await queryRunner.query('DROP INDEX `IDX_77e940a36ec0d2880e9abd1381` ON `song_clears_v2`');
        await queryRunner.query('DROP INDEX `IDX_ca78e5c3139a364014b4d4e9c3` ON `league_ranking`');
        await queryRunner.query('DROP INDEX `IDX_e0232f0a6acb95a3e1db0fd24c` ON `league_ranking`');
        await queryRunner.query('DROP INDEX `IDX_026f5a13d2660022d8093e4952` ON `league_ranking`');
        await queryRunner.query('DROP INDEX `IDX_a878b35267e6fe895ef4bd6041` ON `zz__archive_song_world_records`');
        await queryRunner.query('ALTER TABLE `player_profile_nicknames` DROP FOREIGN KEY `FK_4c610a25fa7ee569d8ef1432b39`');
        await queryRunner.query('ALTER TABLE `player_profile_nicknames` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `player_profile_nicknames` CHANGE `profileId` `profileId` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `player_profile_images` DROP FOREIGN KEY `FK_b88087eafab3747821520e852dc`');
        await queryRunner.query('ALTER TABLE `player_profile_images` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `player_profile_images` CHANGE `profileId` `profileId` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `player_profile_images` CHANGE `profileImage` `profileImage` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `player_profile_images` CHANGE `leaderCardCard_image` `leaderCardCard_image` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `player_profile_images` CHANGE `leaderCardLevel` `leaderCardLevel` smallint UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` DROP FOREIGN KEY `FK_c25b591527001a723e92df13d94`');
        await queryRunner.query('ALTER TABLE `song_world_records` DROP FOREIGN KEY `FK_23476a4ef9023592d8b960f643a`');
        await queryRunner.query('ALTER TABLE `player_profiles` DROP FOREIGN KEY `FK_887adb9d555b50e3909d713f30d`');
        await queryRunner.query('DROP INDEX `IDX_6e575941a0e824087375ecdb5f` ON `player_profiles`');
        await queryRunner.query('ALTER TABLE `player_profiles` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `player_profiles` CHANGE `objectID` `objectID` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `player_profiles` CHANGE `specialUserCode` `specialUserCode` int UNSIGNED NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `player_profiles` CHANGE `divisionGroup` `divisionGroup` tinyint UNSIGNED NULL COMMENT \'in SSRGs the divisions are divided into two groups\'');
        await queryRunner.query('ALTER TABLE `player_profiles` CHANGE `gameId` `gameId` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `score` `score` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `divisionId` `divisionId` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `divisionGroup` `divisionGroup` tinyint UNSIGNED NOT NULL COMMENT \'in SSRGs the divisions are divided into two groups\'');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `isSSRGDiscord` `isSSRGDiscord` tinyint(1) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `objectID` `objectID` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `specialUserCode` `specialUserCode` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `profileId` `profileId` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `gameId` `gameId` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `guid` `guid` varchar(255) NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `song_id` `song_id` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `index_beat_max` `index_beat_max` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `index_beat_min` `index_beat_min` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `count_notes_total` `count_notes_total` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `count_notes_total_raw` `count_notes_total_raw` int UNSIGNED NOT NULL COMMENT \'including all bullshit from the beatmaps\'');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `count_notes_nocombo` `count_notes_nocombo` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `count_taps` `count_taps` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `count_sliders_nocombo` `count_sliders_nocombo` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `count_sliders_total` `count_sliders_total` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `beatmap_date_processed` `beatmap_date_processed` datetime NOT NULL COMMENT \'date when the beatmap has been processed\' DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `difficulty_id` `difficulty_id` smallint UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` ADD UNIQUE INDEX `IDX_dc01d5543b253c5ea2003705b5` (`guid`)');
        await queryRunner.query('ALTER TABLE `world_record_seasons` DROP FOREIGN KEY `FK_954b6470e824ceb15dda0c02567`');
        await queryRunner.query('ALTER TABLE `world_record_seasons` CHANGE `dalcomSeasonId` `dalcomSeasonId` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `world_record_seasons` CHANGE `gameId` `gameId` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `log_credits` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `log_credits` ADD UNIQUE INDEX `IDX_078c7ad329b51a9ca50b30872c` (`guid`)');
        await queryRunner.query('ALTER TABLE `log_diamonds` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `log_diamonds_ads` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `log_diamonds_ads` CHANGE `amount` `amount` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `log_diamonds_ads` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `song_clear_cards` DROP FOREIGN KEY `FK_5d02077d4941019273995220b5d`');
        await queryRunner.query('DROP INDEX `IDX_4f9d43eacf66b2187dc3a4d3e6` ON `song_clear_cards`');
        await queryRunner.query('ALTER TABLE `song_clear_cards` CHANGE `rotation_order` `rotation_order` smallint UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clear_cards` CHANGE `memberOffset` `memberOffset` tinyint UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clear_cards` CHANGE `score` `score` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_clear_cards` CHANGE `theme_id` `theme_id` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clear_cards` CHANGE `level` `level` smallint UNSIGNED NULL DEFAULT 1');
        await queryRunner.query('ALTER TABLE `song_clear_cards` CHANGE `is_prism` `is_prism` tinyint UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('DROP INDEX `IDX_cfcb0b72fa4ff195125caa885a` ON `artists_members`');
        await queryRunner.query('DROP INDEX `IDX_2611da3855f35b965103a1fc97` ON `artists_members`');
        await queryRunner.query('ALTER TABLE `artists_members` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `artists_members` CHANGE `artistId` `artistId` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `artists_members` CHANGE `memberOffset` `memberOffset` tinyint UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `songs` DROP FOREIGN KEY `FK_999ba7dd3c94dd5f9649944a5c6`');
        await queryRunner.query('ALTER TABLE `themes` DROP FOREIGN KEY `FK_e4cb9c54007a543fca28c05cf93`');
        await queryRunner.query('ALTER TABLE `artists` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `artists` CHANGE `cardCount` `cardCount` tinyint UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `artists` CHANGE `imageId` `imageId` varchar(255) NULL DEFAULT NULL');
        await queryRunner.query('ALTER TABLE `artists` CHANGE `gameId` `gameId` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `tags` `tags` text NOT NULL COMMENT \'contains theme tags like "Limited", "Event", "Original"\'');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `frameId` `frameId` int UNSIGNED NOT NULL COMMENT \'ID of the frame cards, for LE/Event cards\' DEFAULT 0');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `prismId` `prismId` int UNSIGNED NOT NULL COMMENT \'ID of the prism bg, GFriend prism cards\' DEFAULT 1');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `cardIdStart` `cardIdStart` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `prismCardIdStart` `prismCardIdStart` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `cardCount` `cardCount` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `artist_id` `artist_id` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `log_drops` DROP FOREIGN KEY `FK_2081b465971c6e81d5447e0f655`');
        await queryRunner.query('DROP INDEX `bySource` ON `log_drops`');
        await queryRunner.query('ALTER TABLE `log_drops` DROP COLUMN `source`');
        await queryRunner.query('ALTER TABLE `log_drops` ADD `source` varchar(255) NOT NULL');
        await queryRunner.query('ALTER TABLE `log_drops` DROP COLUMN `member`');
        await queryRunner.query('ALTER TABLE `log_drops` ADD `member` varchar(255) NULL');
        await queryRunner.query('ALTER TABLE `log_drops` CHANGE `memberOffset` `memberOffset` tinyint UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `log_drops` CHANGE `theme_id` `theme_id` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `log_drops` CHANGE `grade` `grade` enum (\'C\', \'B\', \'A\', \'S\', \'R\', \'30%\', \'100%\') NOT NULL');
        await queryRunner.query('ALTER TABLE `log_drops` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `log_drops` CHANGE `is_prism` `is_prism` tinyint UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `user_credentials` CHANGE `metadata` `metadata` longtext NOT NULL');
        await queryRunner.query('ALTER TABLE `user_credentials` CHANGE `created` `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `user_credentials` CHANGE `updated` `updated` datetime NULL DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `users_logins` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `users_logins` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `users_logins` CHANGE `userId` `userId` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `users_verifications` DROP FOREIGN KEY `FK_41e98794ccf9f055ddab737c9d5`');
        await queryRunner.query('ALTER TABLE `users_verifications` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `users_verifications` CHANGE `created` `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `users_verifications` CHANGE `userId` `userId` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `files` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `files` CHANGE `size` `size` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `files` CHANGE `userId` `userId` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `users` CHANGE `profilePublic` `profilePublic` tinyint(1) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `users` CHANGE `balancePublic` `balancePublic` tinyint(1) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `users` CHANGE `dropsPublic` `dropsPublic` tinyint(1) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `users` CHANGE `playsPublic` `playsPublic` tinyint(1) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `users` CHANGE `forceDarkMode` `forceDarkMode` tinyint(1) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `users` CHANGE `created` `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `users` CHANGE `modified` `modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `users` CHANGE `email` `email` varchar(255) NOT NULL');
        await queryRunner.query('ALTER TABLE `users` CHANGE `active` `active` tinyint(1) NOT NULL DEFAULT 1');
        await queryRunner.query('ALTER TABLE `song_world_records` DROP FOREIGN KEY `FK_78d80285e88cbbe7b7bab1c6b89`');
        await queryRunner.query('ALTER TABLE `song_world_records` DROP FOREIGN KEY `FK_6a49a1d05b2e4b03fd5de359e51`');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `song_id` `song_id` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `object_id` `object_id` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `special_user_code` `special_user_code` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `profileId` `profileId` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `profile_image` `profile_image` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `highscore` `highscore` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `dateObserved` `dateObserved` datetime NOT NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `dateEntry` `dateEntry` datetime NOT NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `rank` `rank` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `season_id` `season_id` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `leaderCardCard_image` `leaderCardCard_image` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `leaderCardLevel` `leaderCardLevel` smallint UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `songs` DROP FOREIGN KEY `FK_ab62eccd228dff0992fcb44f059`');
        await queryRunner.query('DROP INDEX `IDX_b8f348b612eb1b849cbc56b877` ON `songs`');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `length_seconds` `length_seconds` decimal(10,3) NULL COMMENT \'length in seconds\'');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `ingame` `ingame` tinyint UNSIGNED NOT NULL DEFAULT 1');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `dalcom_song_id` `dalcom_song_id` varchar(255) NULL COMMENT \'game internal song id\' DEFAULT NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `imageId` `imageId` varchar(255) NULL COMMENT \'defaults to game internal song id\' DEFAULT NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `dalcom_song_filename` `dalcom_song_filename` varchar(255) NULL COMMENT \'game internal song filename\' DEFAULT NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `game_id` `game_id` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `artist_id` `artist_id` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `beatmap_fingerprint` `beatmap_fingerprint` varchar(255) NULL COMMENT \'game internal song filename\' DEFAULT NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `swrStatHighscore` `swrStatHighscore` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `swrStatMin` `swrStatMin` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `swrStatMean` `swrStatMean` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `swrStatMedian` `swrStatMedian` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` DROP FOREIGN KEY `FK_390b24af470bafbd41bd092b62e`');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `rp_base` `rp_base` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `rp_total` `rp_total` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `rp_bonus` `rp_bonus` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `score_total` `score_total` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `score_base` `score_base` int UNSIGNED NULL COMMENT \'this field can not be relied upon if hit_miss is not zero\'');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `score_rave_bonus` `score_rave_bonus` int UNSIGNED NULL COMMENT \'this field can not be relied upon if hit_miss is not zero\'');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `score_bonus` `score_bonus` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `stars` `stars` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `hit_super_perfect` `hit_super_perfect` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `hit_perfect` `hit_perfect` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `hit_good` `hit_good` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `hit_miss` `hit_miss` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` DROP COLUMN `hit_score`');
        await queryRunner.query('ALTER TABLE `song_clears_v2` ADD `hit_score` int AS (2 * `hit_super_perfect` + 1 * `hit_perfect` + 0.5 * `hit_good` + -10 * `hit_miss`) VIRTUAL NOT NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `theme_level` `theme_level` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `is_challenge` `is_challenge` tinyint UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `has_bonus` `has_bonus` tinyint UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `watched_ads` `watched_ads` tinyint UNSIGNED NOT NULL DEFAULT 1');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `theme_buff_bonus` `theme_buff_bonus` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `score_theme_grade_bonus` `score_theme_grade_bonus` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `user_id` `user_id` int UNSIGNED NOT NULL DEFAULT 20150115');
        await queryRunner.query('ALTER TABLE `divisions` CHANGE `rp_bonus` `rp_bonus` decimal(2,1) NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `divisions` CHANGE `order` `order` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `divisions` CHANGE `group_order` `group_order` int UNSIGNED NOT NULL COMMENT \'order within the group\'');
        await queryRunner.query('ALTER TABLE `league_ranking` DROP FOREIGN KEY `FK_026f5a13d2660022d8093e4952a`');
        await queryRunner.query('ALTER TABLE `league_ranking` DROP FOREIGN KEY `FK_e0232f0a6acb95a3e1db0fd24c5`');
        await queryRunner.query('ALTER TABLE `league_ranking` DROP FOREIGN KEY `FK_ca78e5c3139a364014b4d4e9c34`');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `diff_above` `diff_above` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `diff_below` `diff_below` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `score_above` `score_above` int AS (`score` + `diff_above`) STORED UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `score_below` `score_below` int AS (`score` - `diff_below`) STORED UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `division_id` `division_id` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `user_id` `user_id` int UNSIGNED NULL DEFAULT 20150115');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `game_id` `game_id` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `superstar_games_populations` DROP FOREIGN KEY `FK_56cb7bb50557527fea11e2a2b99`');
        await queryRunner.query('ALTER TABLE `superstar_games_populations` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `superstar_games_populations` CHANGE `population` `population` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `superstar_games_populations` CHANGE `gameId` `gameId` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `zz_gamedata_manifests` DROP FOREIGN KEY `FK_b44767288778601ef1e49033985`');
        await queryRunner.query('DROP INDEX `perGameAndVersion` ON `zz_gamedata_manifests`');
        await queryRunner.query('ALTER TABLE `zz_gamedata_manifests` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `zz_gamedata_manifests` CHANGE `gameId` `gameId` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `zz_gamedata_manifests` CHANGE `data` `data` longtext NOT NULL');
        await queryRunner.query('ALTER TABLE `zz_gamedata_files` DROP FOREIGN KEY `FK_ec1d70d65bd4292f0c80ccc2eb0`');
        await queryRunner.query('DROP INDEX `perGameAndVersionAndKey` ON `zz_gamedata_files`');
        await queryRunner.query('ALTER TABLE `zz_gamedata_files` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `zz_gamedata_files` CHANGE `gameId` `gameId` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `zz_gamedata_files` CHANGE `version` `version` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `superstar_games` CHANGE `max_r_level` `max_r_level` smallint UNSIGNED NULL DEFAULT 50');
        await queryRunner.query('ALTER TABLE `superstar_games` CHANGE `active` `active` tinyint UNSIGNED NOT NULL COMMENT \'whether this entry is active in the application and should be displayed and interacted with\' DEFAULT 1');
        await queryRunner.query('ALTER TABLE `superstar_games` CHANGE `hasPrism` `hasPrism` tinyint UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `superstar_games` CHANGE `isSingleArtistGame` `isSingleArtistGame` tinyint UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('DROP INDEX `bySongAndSeason` ON `zz__archive_song_world_records`');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` CHANGE `gameId` `gameId` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` CHANGE `songCode` `songCode` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` CHANGE `seasonCode` `seasonCode` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` ADD UNIQUE INDEX `IDX_c74470b87f73827918607f87db` (`guid`)');
        await queryRunner.query('ALTER TABLE `oauth_codes` DROP FOREIGN KEY `FK_1e80210c80509097733e5194bda`');
        await queryRunner.query('ALTER TABLE `oauth_codes` DROP FOREIGN KEY `FK_4dac391deea4c1f8d24a63107b2`');
        await queryRunner.query('ALTER TABLE `oauth_codes` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `oauth_codes` CHANGE `clientId` `clientId` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `oauth_codes` CHANGE `userId` `userId` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `oauth_tokens` DROP FOREIGN KEY `FK_3d9dfb37837e5dd891bbc81b324`');
        await queryRunner.query('ALTER TABLE `oauth_tokens` DROP FOREIGN KEY `FK_a8c200cc4c90d24e832caf0a180`');
        await queryRunner.query('ALTER TABLE `oauth_tokens` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `oauth_tokens` CHANGE `clientId` `clientId` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `oauth_tokens` CHANGE `userId` `userId` int UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `oauth_clients` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `users_active_games_superstar_games` DROP FOREIGN KEY `FK_249c319fce0d6f0d6bf84a0de9b`');
        await queryRunner.query('ALTER TABLE `users_active_games_superstar_games` DROP FOREIGN KEY `FK_73cd963bb92f6f0feed8a193498`');
        await queryRunner.query('ALTER TABLE `users_active_games_superstar_games` CHANGE `usersId` `usersId` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `users_active_games_superstar_games` CHANGE `superstarGamesId` `superstarGamesId` int UNSIGNED NOT NULL');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_6e575941a0e824087375ecdb5f` ON `player_profiles` (`objectID`, `gameId`)');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_4f9d43eacf66b2187dc3a4d3e6` ON `song_clear_cards` (`song_clear_id`, `rotation_order`)');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_1172436d985c8607f8098511af` ON `song_clear_cards` (`song_clear_id`, `memberOffset`)');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_cfcb0b72fa4ff195125caa885a` ON `artists_members` (`artistId`, `memberOffset`)');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_2611da3855f35b965103a1fc97` ON `artists_members` (`artistId`, `name`)');
        await queryRunner.query('CREATE INDEX `bySource` ON `log_drops` (`source`)');
        await queryRunner.query('CREATE INDEX `byDateObserved` ON `song_world_records` (`dateObserved`)');
        await queryRunner.query('CREATE INDEX `byDateEntry` ON `song_world_records` (`dateEntry`)');
        await queryRunner.query('CREATE INDEX `byRank` ON `song_world_records` (`rank`)');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_b8f348b612eb1b849cbc56b877` ON `songs` (`dalcom_song_id`, `game_id`)');
        await queryRunner.query('CREATE UNIQUE INDEX `perGameAndVersion` ON `zz_gamedata_manifests` (`gameId`, `versionString`)');
        await queryRunner.query('CREATE UNIQUE INDEX `perGameAndVersionAndKey` ON `zz_gamedata_files` (`gameId`, `version`, `key`)');
        await queryRunner.query('CREATE INDEX `bySongAndSeason` ON `zz__archive_song_world_records` (`gameId`, `songCode`, `seasonCode`)');
        await queryRunner.query('ALTER TABLE `player_profile_nicknames` ADD CONSTRAINT `FK_4c610a25fa7ee569d8ef1432b39` FOREIGN KEY (`profileId`) REFERENCES `player_profiles`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `player_profile_images` ADD CONSTRAINT `FK_b88087eafab3747821520e852dc` FOREIGN KEY (`profileId`) REFERENCES `player_profiles`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `player_profiles` ADD CONSTRAINT `FK_887adb9d555b50e3909d713f30d` FOREIGN KEY (`gameId`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `league_tracker` ADD CONSTRAINT `FK_c25b591527001a723e92df13d94` FOREIGN KEY (`profileId`) REFERENCES `player_profiles`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `league_tracker` ADD CONSTRAINT `FK_417cc8ee83919806f8e9b1985bb` FOREIGN KEY (`divisionId`) REFERENCES `divisions`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `league_tracker` ADD CONSTRAINT `FK_4379339864ebf7b33a6524e8ea0` FOREIGN KEY (`gameId`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `song_beatmaps` ADD CONSTRAINT `FK_2f31b74a91bfc42a993040d70bc` FOREIGN KEY (`song_id`) REFERENCES `songs`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `world_record_seasons` ADD CONSTRAINT `FK_954b6470e824ceb15dda0c02567` FOREIGN KEY (`gameId`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `song_clear_cards` ADD CONSTRAINT `FK_5d02077d4941019273995220b5d` FOREIGN KEY (`theme_id`) REFERENCES `themes`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `artists_members` ADD CONSTRAINT `FK_026669fdd653985ef388610f523` FOREIGN KEY (`artistId`) REFERENCES `artists`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `artists` ADD CONSTRAINT `FK_4398e9cd012cad58e0ac8311848` FOREIGN KEY (`gameId`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `themes` ADD CONSTRAINT `FK_e4cb9c54007a543fca28c05cf93` FOREIGN KEY (`artist_id`) REFERENCES `artists`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `log_drops` ADD CONSTRAINT `FK_2081b465971c6e81d5447e0f655` FOREIGN KEY (`theme_id`) REFERENCES `themes`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `users_logins` ADD CONSTRAINT `FK_684ca10a98fc881a400044e37dc` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `users_verifications` ADD CONSTRAINT `FK_41e98794ccf9f055ddab737c9d5` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `files` ADD CONSTRAINT `FK_7e7425b17f9e707331e9a6c7335` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `song_world_records` ADD CONSTRAINT `FK_6a49a1d05b2e4b03fd5de359e51` FOREIGN KEY (`season_id`) REFERENCES `world_record_seasons`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `song_world_records` ADD CONSTRAINT `FK_07bb2b86ae073281d18a6ecabb5` FOREIGN KEY (`observerUserId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `song_world_records` ADD CONSTRAINT `FK_23476a4ef9023592d8b960f643a` FOREIGN KEY (`profileId`) REFERENCES `player_profiles`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `song_world_records` ADD CONSTRAINT `FK_78d80285e88cbbe7b7bab1c6b89` FOREIGN KEY (`song_id`) REFERENCES `songs`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `songs` ADD CONSTRAINT `FK_999ba7dd3c94dd5f9649944a5c6` FOREIGN KEY (`artist_id`) REFERENCES `artists`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `songs` ADD CONSTRAINT `FK_ab62eccd228dff0992fcb44f059` FOREIGN KEY (`game_id`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `song_clears_v2` ADD CONSTRAINT `FK_390b24af470bafbd41bd092b62e` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `league_ranking` ADD CONSTRAINT `FK_026f5a13d2660022d8093e4952a` FOREIGN KEY (`division_id`) REFERENCES `divisions`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `league_ranking` ADD CONSTRAINT `FK_e0232f0a6acb95a3e1db0fd24c5` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `league_ranking` ADD CONSTRAINT `FK_ca78e5c3139a364014b4d4e9c34` FOREIGN KEY (`game_id`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `superstar_games_populations` ADD CONSTRAINT `FK_56cb7bb50557527fea11e2a2b99` FOREIGN KEY (`gameId`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `zz_gamedata_manifests` ADD CONSTRAINT `FK_b44767288778601ef1e49033985` FOREIGN KEY (`gameId`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `zz_gamedata_files` ADD CONSTRAINT `FK_ec1d70d65bd4292f0c80ccc2eb0` FOREIGN KEY (`gameId`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` ADD CONSTRAINT `FK_95cf44f9725771980f56017f7e4` FOREIGN KEY (`gameId`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `oauth_codes` ADD CONSTRAINT `FK_1e80210c80509097733e5194bda` FOREIGN KEY (`clientId`) REFERENCES `oauth_clients`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `oauth_codes` ADD CONSTRAINT `FK_4dac391deea4c1f8d24a63107b2` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `oauth_tokens` ADD CONSTRAINT `FK_3d9dfb37837e5dd891bbc81b324` FOREIGN KEY (`clientId`) REFERENCES `oauth_clients`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `oauth_tokens` ADD CONSTRAINT `FK_a8c200cc4c90d24e832caf0a180` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `users_active_games_superstar_games` ADD CONSTRAINT `FK_249c319fce0d6f0d6bf84a0de9b` FOREIGN KEY (`usersId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE `users_active_games_superstar_games` ADD CONSTRAINT `FK_73cd963bb92f6f0feed8a193498` FOREIGN KEY (`superstarGamesId`) REFERENCES `superstar_games`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION');
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('ALTER TABLE `users_active_games_superstar_games` DROP FOREIGN KEY `FK_73cd963bb92f6f0feed8a193498`');
        await queryRunner.query('ALTER TABLE `users_active_games_superstar_games` DROP FOREIGN KEY `FK_249c319fce0d6f0d6bf84a0de9b`');
        await queryRunner.query('ALTER TABLE `oauth_tokens` DROP FOREIGN KEY `FK_a8c200cc4c90d24e832caf0a180`');
        await queryRunner.query('ALTER TABLE `oauth_tokens` DROP FOREIGN KEY `FK_3d9dfb37837e5dd891bbc81b324`');
        await queryRunner.query('ALTER TABLE `oauth_codes` DROP FOREIGN KEY `FK_4dac391deea4c1f8d24a63107b2`');
        await queryRunner.query('ALTER TABLE `oauth_codes` DROP FOREIGN KEY `FK_1e80210c80509097733e5194bda`');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` DROP FOREIGN KEY `FK_95cf44f9725771980f56017f7e4`');
        await queryRunner.query('ALTER TABLE `zz_gamedata_files` DROP FOREIGN KEY `FK_ec1d70d65bd4292f0c80ccc2eb0`');
        await queryRunner.query('ALTER TABLE `zz_gamedata_manifests` DROP FOREIGN KEY `FK_b44767288778601ef1e49033985`');
        await queryRunner.query('ALTER TABLE `superstar_games_populations` DROP FOREIGN KEY `FK_56cb7bb50557527fea11e2a2b99`');
        await queryRunner.query('ALTER TABLE `league_ranking` DROP FOREIGN KEY `FK_ca78e5c3139a364014b4d4e9c34`');
        await queryRunner.query('ALTER TABLE `league_ranking` DROP FOREIGN KEY `FK_e0232f0a6acb95a3e1db0fd24c5`');
        await queryRunner.query('ALTER TABLE `league_ranking` DROP FOREIGN KEY `FK_026f5a13d2660022d8093e4952a`');
        await queryRunner.query('ALTER TABLE `song_clears_v2` DROP FOREIGN KEY `FK_390b24af470bafbd41bd092b62e`');
        await queryRunner.query('ALTER TABLE `songs` DROP FOREIGN KEY `FK_ab62eccd228dff0992fcb44f059`');
        await queryRunner.query('ALTER TABLE `songs` DROP FOREIGN KEY `FK_999ba7dd3c94dd5f9649944a5c6`');
        await queryRunner.query('ALTER TABLE `song_world_records` DROP FOREIGN KEY `FK_78d80285e88cbbe7b7bab1c6b89`');
        await queryRunner.query('ALTER TABLE `song_world_records` DROP FOREIGN KEY `FK_23476a4ef9023592d8b960f643a`');
        await queryRunner.query('ALTER TABLE `song_world_records` DROP FOREIGN KEY `FK_07bb2b86ae073281d18a6ecabb5`');
        await queryRunner.query('ALTER TABLE `song_world_records` DROP FOREIGN KEY `FK_6a49a1d05b2e4b03fd5de359e51`');
        await queryRunner.query('ALTER TABLE `files` DROP FOREIGN KEY `FK_7e7425b17f9e707331e9a6c7335`');
        await queryRunner.query('ALTER TABLE `users_verifications` DROP FOREIGN KEY `FK_41e98794ccf9f055ddab737c9d5`');
        await queryRunner.query('ALTER TABLE `users_logins` DROP FOREIGN KEY `FK_684ca10a98fc881a400044e37dc`');
        await queryRunner.query('ALTER TABLE `log_drops` DROP FOREIGN KEY `FK_2081b465971c6e81d5447e0f655`');
        await queryRunner.query('ALTER TABLE `themes` DROP FOREIGN KEY `FK_e4cb9c54007a543fca28c05cf93`');
        await queryRunner.query('ALTER TABLE `artists` DROP FOREIGN KEY `FK_4398e9cd012cad58e0ac8311848`');
        await queryRunner.query('ALTER TABLE `artists_members` DROP FOREIGN KEY `FK_026669fdd653985ef388610f523`');
        await queryRunner.query('ALTER TABLE `song_clear_cards` DROP FOREIGN KEY `FK_5d02077d4941019273995220b5d`');
        await queryRunner.query('ALTER TABLE `world_record_seasons` DROP FOREIGN KEY `FK_954b6470e824ceb15dda0c02567`');
        await queryRunner.query('ALTER TABLE `song_beatmaps` DROP FOREIGN KEY `FK_2f31b74a91bfc42a993040d70bc`');
        await queryRunner.query('ALTER TABLE `league_tracker` DROP FOREIGN KEY `FK_4379339864ebf7b33a6524e8ea0`');
        await queryRunner.query('ALTER TABLE `league_tracker` DROP FOREIGN KEY `FK_417cc8ee83919806f8e9b1985bb`');
        await queryRunner.query('ALTER TABLE `league_tracker` DROP FOREIGN KEY `FK_c25b591527001a723e92df13d94`');
        await queryRunner.query('ALTER TABLE `player_profiles` DROP FOREIGN KEY `FK_887adb9d555b50e3909d713f30d`');
        await queryRunner.query('ALTER TABLE `player_profile_images` DROP FOREIGN KEY `FK_b88087eafab3747821520e852dc`');
        await queryRunner.query('ALTER TABLE `player_profile_nicknames` DROP FOREIGN KEY `FK_4c610a25fa7ee569d8ef1432b39`');
        await queryRunner.query('DROP INDEX `bySongAndSeason` ON `zz__archive_song_world_records`');
        await queryRunner.query('DROP INDEX `perGameAndVersionAndKey` ON `zz_gamedata_files`');
        await queryRunner.query('DROP INDEX `perGameAndVersion` ON `zz_gamedata_manifests`');
        await queryRunner.query('DROP INDEX `IDX_b8f348b612eb1b849cbc56b877` ON `songs`');
        await queryRunner.query('DROP INDEX `byRank` ON `song_world_records`');
        await queryRunner.query('DROP INDEX `byDateEntry` ON `song_world_records`');
        await queryRunner.query('DROP INDEX `byDateObserved` ON `song_world_records`');
        await queryRunner.query('DROP INDEX `bySource` ON `log_drops`');
        await queryRunner.query('DROP INDEX `IDX_2611da3855f35b965103a1fc97` ON `artists_members`');
        await queryRunner.query('DROP INDEX `IDX_cfcb0b72fa4ff195125caa885a` ON `artists_members`');
        await queryRunner.query('DROP INDEX `IDX_1172436d985c8607f8098511af` ON `song_clear_cards`');
        await queryRunner.query('DROP INDEX `IDX_4f9d43eacf66b2187dc3a4d3e6` ON `song_clear_cards`');
        await queryRunner.query('DROP INDEX `IDX_6e575941a0e824087375ecdb5f` ON `player_profiles`');
        await queryRunner.query('ALTER TABLE `users_active_games_superstar_games` CHANGE `superstarGamesId` `superstarGamesId` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `users_active_games_superstar_games` CHANGE `usersId` `usersId` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `users_active_games_superstar_games` ADD CONSTRAINT `FK_73cd963bb92f6f0feed8a193498` FOREIGN KEY (`superstarGamesId`, `superstarGamesId`) REFERENCES `superstar_games`(`id`,`id`) ON DELETE CASCADE ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE `users_active_games_superstar_games` ADD CONSTRAINT `FK_249c319fce0d6f0d6bf84a0de9b` FOREIGN KEY (`usersId`, `usersId`) REFERENCES `users`(`id`,`id`) ON DELETE CASCADE ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE `oauth_clients` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `oauth_tokens` CHANGE `userId` `userId` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `oauth_tokens` CHANGE `clientId` `clientId` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `oauth_tokens` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `oauth_tokens` ADD CONSTRAINT `FK_a8c200cc4c90d24e832caf0a180` FOREIGN KEY (`userId`, `userId`) REFERENCES `users`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `oauth_tokens` ADD CONSTRAINT `FK_3d9dfb37837e5dd891bbc81b324` FOREIGN KEY (`clientId`, `clientId`) REFERENCES `oauth_clients`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `oauth_codes` CHANGE `userId` `userId` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `oauth_codes` CHANGE `clientId` `clientId` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `oauth_codes` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `oauth_codes` ADD CONSTRAINT `FK_4dac391deea4c1f8d24a63107b2` FOREIGN KEY (`userId`, `userId`) REFERENCES `users`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `oauth_codes` ADD CONSTRAINT `FK_1e80210c80509097733e5194bda` FOREIGN KEY (`clientId`, `clientId`) REFERENCES `oauth_clients`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` DROP INDEX `IDX_c74470b87f73827918607f87db`');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` CHANGE `seasonCode` `seasonCode` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` CHANGE `songCode` `songCode` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` CHANGE `gameId` `gameId` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('CREATE INDEX `bySongAndSeason` ON `zz__archive_song_world_records` (`gameId`, `songCode`, `seasonCode`)');
        await queryRunner.query('ALTER TABLE `superstar_games` CHANGE `isSingleArtistGame` `isSingleArtistGame` tinyint(3) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `superstar_games` CHANGE `hasPrism` `hasPrism` tinyint(3) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `superstar_games` CHANGE `active` `active` tinyint(3) UNSIGNED NOT NULL COMMENT \'whether this entry is active in the application and should be displayed and interacted with\' DEFAULT 1');
        await queryRunner.query('ALTER TABLE `superstar_games` CHANGE `max_r_level` `max_r_level` smallint(5) UNSIGNED NULL DEFAULT 50');
        await queryRunner.query('ALTER TABLE `zz_gamedata_files` CHANGE `version` `version` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `zz_gamedata_files` CHANGE `gameId` `gameId` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `zz_gamedata_files` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('CREATE UNIQUE INDEX `perGameAndVersionAndKey` ON `zz_gamedata_files` (`gameId`, `version`, `key`)');
        await queryRunner.query('ALTER TABLE `zz_gamedata_files` ADD CONSTRAINT `FK_ec1d70d65bd4292f0c80ccc2eb0` FOREIGN KEY (`gameId`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `zz_gamedata_manifests` CHANGE `data` `data` longtext NOT NULL DEFAULT \'\'');
        await queryRunner.query('ALTER TABLE `zz_gamedata_manifests` CHANGE `gameId` `gameId` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `zz_gamedata_manifests` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('CREATE UNIQUE INDEX `perGameAndVersion` ON `zz_gamedata_manifests` (`gameId`, `versionString`)');
        await queryRunner.query('ALTER TABLE `zz_gamedata_manifests` ADD CONSTRAINT `FK_b44767288778601ef1e49033985` FOREIGN KEY (`gameId`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `superstar_games_populations` CHANGE `gameId` `gameId` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `superstar_games_populations` CHANGE `population` `population` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `superstar_games_populations` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `superstar_games_populations` ADD CONSTRAINT `FK_56cb7bb50557527fea11e2a2b99` FOREIGN KEY (`gameId`, `gameId`) REFERENCES `superstar_games`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `game_id` `game_id` int UNSIGNED NOT NULL DEFAULT 1');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `user_id` `user_id` int(10) UNSIGNED NULL DEFAULT 20150115');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `division_id` `division_id` int UNSIGNED NOT NULL DEFAULT 7');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `score_below` `score_below` int AS (`score` - `diff_below`) STORED NULL');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `score_above` `score_above` int AS (`score` + `diff_above`) STORED NULL');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `diff_below` `diff_below` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_ranking` CHANGE `diff_above` `diff_above` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_ranking` ADD CONSTRAINT `FK_ca78e5c3139a364014b4d4e9c34` FOREIGN KEY (`game_id`, `game_id`) REFERENCES `superstar_games`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `league_ranking` ADD CONSTRAINT `FK_e0232f0a6acb95a3e1db0fd24c5` FOREIGN KEY (`user_id`, `user_id`) REFERENCES `users`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `league_ranking` ADD CONSTRAINT `FK_026f5a13d2660022d8093e4952a` FOREIGN KEY (`division_id`, `division_id`) REFERENCES `divisions`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `divisions` CHANGE `group_order` `group_order` int(10) UNSIGNED NOT NULL COMMENT \'order within the group\'');
        await queryRunner.query('ALTER TABLE `divisions` CHANGE `order` `order` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `divisions` CHANGE `rp_bonus` `rp_bonus` decimal(2,1) NOT NULL DEFAULT 0.0');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `user_id` `user_id` int UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `score_theme_grade_bonus` `score_theme_grade_bonus` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `theme_buff_bonus` `theme_buff_bonus` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `watched_ads` `watched_ads` tinyint(3) UNSIGNED NOT NULL DEFAULT 1');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `has_bonus` `has_bonus` tinyint(3) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `is_challenge` `is_challenge` tinyint(3) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `theme_level` `theme_level` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` DROP COLUMN `hit_score`');
        await queryRunner.query('ALTER TABLE `song_clears_v2` ADD `hit_score` int AS (2 * coalesce(`hit_super_perfect`,0) + 1 * coalesce(`hit_perfect`,0) + 0.5 * coalesce(`hit_good`,0) + -10 * coalesce(`hit_miss`,0)) STORED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `hit_miss` `hit_miss` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `hit_good` `hit_good` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `hit_perfect` `hit_perfect` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `hit_super_perfect` `hit_super_perfect` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `stars` `stars` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `score_bonus` `score_bonus` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `score_rave_bonus` `score_rave_bonus` int(10) UNSIGNED NULL COMMENT \'this field can not be relied upon if hit_miss is not zero\'');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `score_base` `score_base` int(10) UNSIGNED NULL COMMENT \'this field can not be relied upon if hit_miss is not zero\'');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `score_total` `score_total` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `rp_bonus` `rp_bonus` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `rp_total` `rp_total` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `rp_base` `rp_base` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clears_v2` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `song_clears_v2` ADD CONSTRAINT `FK_390b24af470bafbd41bd092b62e` FOREIGN KEY (`user_id`, `user_id`) REFERENCES `users`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `swrStatMedian` `swrStatMedian` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `swrStatMean` `swrStatMean` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `swrStatMin` `swrStatMin` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `swrStatHighscore` `swrStatHighscore` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `beatmap_fingerprint` `beatmap_fingerprint` varchar(255) NULL COMMENT \'game internal song filename\'');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `artist_id` `artist_id` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `game_id` `game_id` int UNSIGNED NOT NULL DEFAULT 1');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `dalcom_song_filename` `dalcom_song_filename` varchar(255) NULL COMMENT \'game internal song filename\'');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `imageId` `imageId` varchar(255) NULL COMMENT \'defaults to game internal song id\'');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `dalcom_song_id` `dalcom_song_id` varchar(255) NULL COMMENT \'game internal song id\'');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `ingame` `ingame` tinyint(1) UNSIGNED NOT NULL DEFAULT 1');
        await queryRunner.query('ALTER TABLE `songs` CHANGE `length_seconds` `length_seconds` decimal(10,6) NULL');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_b8f348b612eb1b849cbc56b877` ON `songs` (`dalcom_song_id`, `game_id`)');
        await queryRunner.query('ALTER TABLE `songs` ADD CONSTRAINT `FK_ab62eccd228dff0992fcb44f059` FOREIGN KEY (`game_id`, `game_id`) REFERENCES `superstar_games`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `leaderCardLevel` `leaderCardLevel` smallint(5) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `leaderCardCard_image` `leaderCardCard_image` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `season_id` `season_id` int UNSIGNED NOT NULL DEFAULT 1');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `rank` `rank` int(10) UNSIGNED NULL DEFAULT 1');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `dateEntry` `dateEntry` datetime NULL COMMENT \'date the entry has been entered into the database, e.g. time the script ran or the API call was received\'');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `dateObserved` `dateObserved` datetime NULL COMMENT \'date the entry has been observed, e.g. file date of the json\'');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `highscore` `highscore` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `profile_image` `profile_image` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `profileId` `profileId` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `special_user_code` `special_user_code` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `object_id` `object_id` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `song_id` `song_id` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_world_records` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `song_world_records` ADD CONSTRAINT `FK_6a49a1d05b2e4b03fd5de359e51` FOREIGN KEY (`season_id`, `season_id`) REFERENCES `world_record_seasons`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `song_world_records` ADD CONSTRAINT `FK_78d80285e88cbbe7b7bab1c6b89` FOREIGN KEY (`song_id`, `song_id`) REFERENCES `songs`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `users` CHANGE `active` `active` tinyint(4) NOT NULL DEFAULT 1');
        await queryRunner.query('ALTER TABLE `users` CHANGE `email` `email` varchar(255) NULL');
        await queryRunner.query('ALTER TABLE `users` CHANGE `modified` `modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `users` CHANGE `created` `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `users` CHANGE `forceDarkMode` `forceDarkMode` tinyint(3) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `users` CHANGE `playsPublic` `playsPublic` tinyint(3) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `users` CHANGE `dropsPublic` `dropsPublic` tinyint(3) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `users` CHANGE `balancePublic` `balancePublic` tinyint(3) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `users` CHANGE `profilePublic` `profilePublic` tinyint(3) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `files` CHANGE `userId` `userId` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `files` CHANGE `size` `size` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `files` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `users_verifications` CHANGE `userId` `userId` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `users_verifications` CHANGE `created` `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `users_verifications` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `users_verifications` ADD CONSTRAINT `FK_41e98794ccf9f055ddab737c9d5` FOREIGN KEY (`userId`, `userId`) REFERENCES `users`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `users_logins` CHANGE `userId` `userId` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `users_logins` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `users_logins` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `user_credentials` CHANGE `updated` `updated` datetime NULL DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `user_credentials` CHANGE `created` `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `user_credentials` CHANGE `metadata` `metadata` longtext COLLATE "utf8mb4_bin" NOT NULL DEFAULT \'{}\'');
        await queryRunner.query('ALTER TABLE `log_drops` CHANGE `is_prism` `is_prism` tinyint(3) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `log_drops` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `log_drops` CHANGE `grade` `grade` enum (\'C\', \'B\', \'A\', \'S\', \'R\', \'30%\', \'70%\', \'100%\') NOT NULL');
        await queryRunner.query('ALTER TABLE `log_drops` CHANGE `theme_id` `theme_id` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `log_drops` CHANGE `memberOffset` `memberOffset` tinyint(3) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `log_drops` DROP COLUMN `member`');
        await queryRunner.query('ALTER TABLE `log_drops` ADD `member` enum (\'Sowon\', \'Yerin\', \'Eunha\', \'Yuju\', \'SinB\', \'Umji\', \'Power Up\') NULL');
        await queryRunner.query('ALTER TABLE `log_drops` DROP COLUMN `source`');
        await queryRunner.query('ALTER TABLE `log_drops` ADD `source` enum (\'Purchase (Diamond\') NOT NULL');
        await queryRunner.query('CREATE INDEX `bySource` ON `log_drops` (`source`)');
        await queryRunner.query('ALTER TABLE `log_drops` ADD CONSTRAINT `FK_2081b465971c6e81d5447e0f655` FOREIGN KEY (`theme_id`, `theme_id`) REFERENCES `themes`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `artist_id` `artist_id` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `cardCount` `cardCount` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `prismCardIdStart` `prismCardIdStart` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `cardIdStart` `cardIdStart` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `prismId` `prismId` int(10) UNSIGNED NOT NULL COMMENT \'ID of the prism bg, GFriend prism cards\' DEFAULT 1');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `frameId` `frameId` int(10) UNSIGNED NOT NULL COMMENT \'ID of the frame cards, for LE/Event cards\' DEFAULT 0');
        await queryRunner.query('ALTER TABLE `themes` CHANGE `tags` `tags` text NOT NULL COMMENT \'contains theme tags like "Limited", "Event", "Original"\' DEFAULT \'\'');
        await queryRunner.query('ALTER TABLE `artists` CHANGE `gameId` `gameId` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `artists` CHANGE `imageId` `imageId` varchar(255) NULL');
        await queryRunner.query('ALTER TABLE `artists` CHANGE `cardCount` `cardCount` tinyint(3) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `artists` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `themes` ADD CONSTRAINT `FK_e4cb9c54007a543fca28c05cf93` FOREIGN KEY (`artist_id`, `artist_id`) REFERENCES `artists`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `songs` ADD CONSTRAINT `FK_999ba7dd3c94dd5f9649944a5c6` FOREIGN KEY (`artist_id`, `artist_id`) REFERENCES `artists`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `artists_members` CHANGE `memberOffset` `memberOffset` tinyint(3) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `artists_members` CHANGE `artistId` `artistId` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `artists_members` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_2611da3855f35b965103a1fc97` ON `artists_members` (`artistId`, `name`)');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_cfcb0b72fa4ff195125caa885a` ON `artists_members` (`artistId`, `memberOffset`)');
        await queryRunner.query('ALTER TABLE `song_clear_cards` CHANGE `is_prism` `is_prism` tinyint(3) UNSIGNED NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `song_clear_cards` CHANGE `level` `level` smallint(5) UNSIGNED NULL DEFAULT 1');
        await queryRunner.query('ALTER TABLE `song_clear_cards` CHANGE `grade` `grade` enum (\'None\', \'C\', \'B\', \'A\', \'S\', \'R\') NOT NULL DEFAULT \'S\'');
        await queryRunner.query('ALTER TABLE `song_clear_cards` CHANGE `theme_id` `theme_id` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clear_cards` CHANGE `score` `score` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_clear_cards` CHANGE `memberOffset` `memberOffset` tinyint(3) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `song_clear_cards` CHANGE `rotation_order` `rotation_order` smallint(5) UNSIGNED NULL');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_4f9d43eacf66b2187dc3a4d3e6` ON `song_clear_cards` (`song_clear_id`, `rotation_order`)');
        await queryRunner.query('ALTER TABLE `song_clear_cards` ADD CONSTRAINT `FK_5d02077d4941019273995220b5d` FOREIGN KEY (`theme_id`, `theme_id`) REFERENCES `themes`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `log_diamonds_ads` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `log_diamonds_ads` CHANGE `amount` `amount` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `log_diamonds_ads` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `log_diamonds` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `log_credits` DROP INDEX `IDX_078c7ad329b51a9ca50b30872c`');
        await queryRunner.query('ALTER TABLE `log_credits` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `world_record_seasons` CHANGE `gameId` `gameId` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `world_record_seasons` CHANGE `dalcomSeasonId` `dalcomSeasonId` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `world_record_seasons` ADD CONSTRAINT `FK_954b6470e824ceb15dda0c02567` FOREIGN KEY (`gameId`, `gameId`) REFERENCES `superstar_games`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `song_beatmaps` DROP INDEX `IDX_dc01d5543b253c5ea2003705b5`');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `difficulty_id` `difficulty_id` smallint(5) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `beatmap_date_processed` `beatmap_date_processed` datetime NOT NULL COMMENT \'date when the beatmap has been processed\' DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `count_sliders_total` `count_sliders_total` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `count_sliders_nocombo` `count_sliders_nocombo` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `count_taps` `count_taps` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `count_notes_nocombo` `count_notes_nocombo` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `count_notes_total_raw` `count_notes_total_raw` int(10) UNSIGNED NOT NULL COMMENT \'including all bullshit from the beatmaps\'');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `count_notes_total` `count_notes_total` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `index_beat_min` `index_beat_min` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `index_beat_max` `index_beat_max` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `song_id` `song_id` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `song_beatmaps` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `guid` `guid` varchar(255) NOT NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `gameId` `gameId` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `profileId` `profileId` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `specialUserCode` `specialUserCode` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `objectID` `objectID` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `isSSRGDiscord` `isSSRGDiscord` tinyint(1) NOT NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `divisionGroup` `divisionGroup` tinyint(3) UNSIGNED NOT NULL COMMENT \'in SSRGs the divisions are divided into two groups\'');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `divisionId` `divisionId` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `score` `score` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `league_tracker` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `player_profiles` CHANGE `gameId` `gameId` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `player_profiles` CHANGE `divisionGroup` `divisionGroup` tinyint(3) UNSIGNED NULL COMMENT \'in SSRGs the divisions are divided into two groups\'');
        await queryRunner.query('ALTER TABLE `player_profiles` CHANGE `specialUserCode` `specialUserCode` int(10) UNSIGNED NULL DEFAULT 0');
        await queryRunner.query('ALTER TABLE `player_profiles` CHANGE `objectID` `objectID` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `player_profiles` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_6e575941a0e824087375ecdb5f` ON `player_profiles` (`objectID`, `gameId`)');
        await queryRunner.query('ALTER TABLE `player_profiles` ADD CONSTRAINT `FK_887adb9d555b50e3909d713f30d` FOREIGN KEY (`gameId`, `gameId`) REFERENCES `superstar_games`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `song_world_records` ADD CONSTRAINT `FK_23476a4ef9023592d8b960f643a` FOREIGN KEY (`profileId`, `profileId`) REFERENCES `player_profiles`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `league_tracker` ADD CONSTRAINT `FK_c25b591527001a723e92df13d94` FOREIGN KEY (`profileId`, `profileId`) REFERENCES `player_profiles`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `player_profile_images` CHANGE `leaderCardLevel` `leaderCardLevel` smallint(5) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `player_profile_images` CHANGE `leaderCardCard_image` `leaderCardCard_image` int(10) UNSIGNED NULL');
        await queryRunner.query('ALTER TABLE `player_profile_images` CHANGE `profileImage` `profileImage` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `player_profile_images` CHANGE `profileId` `profileId` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `player_profile_images` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `player_profile_images` ADD CONSTRAINT `FK_b88087eafab3747821520e852dc` FOREIGN KEY (`profileId`, `profileId`) REFERENCES `player_profiles`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `player_profile_nicknames` CHANGE `profileId` `profileId` int(10) UNSIGNED NOT NULL');
        await queryRunner.query('ALTER TABLE `player_profile_nicknames` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
        await queryRunner.query('ALTER TABLE `player_profile_nicknames` ADD CONSTRAINT `FK_4c610a25fa7ee569d8ef1432b39` FOREIGN KEY (`profileId`, `profileId`) REFERENCES `player_profiles`(`id`,`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_a878b35267e6fe895ef4bd6041` ON `zz__archive_song_world_records` (`guid`)');
        await queryRunner.query('CREATE INDEX `IDX_026f5a13d2660022d8093e4952` ON `league_ranking` (`division_id`)');
        await queryRunner.query('CREATE INDEX `IDX_e0232f0a6acb95a3e1db0fd24c` ON `league_ranking` (`user_id`)');
        await queryRunner.query('CREATE INDEX `IDX_ca78e5c3139a364014b4d4e9c3` ON `league_ranking` (`game_id`)');
        await queryRunner.query('CREATE INDEX `IDX_77e940a36ec0d2880e9abd1381` ON `song_clears_v2` (`song_id`)');
        await queryRunner.query('CREATE INDEX `IDX_9be7492417d7ba450d31b0a8a2` ON `song_clears_v2` (`division_id`)');
        await queryRunner.query('CREATE INDEX `IDX_390b24af470bafbd41bd092b62` ON `song_clears_v2` (`user_id`)');
        await queryRunner.query('CREATE INDEX `IDX_ab62eccd228dff0992fcb44f05` ON `songs` (`game_id`)');
        await queryRunner.query('CREATE INDEX `IDX_fefab589657440640cfda575fd` ON `song_world_records` (`date_recorded`)');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_a3ffb1c0c8416b9fc6f907b743` ON `users` (`id`)');
        await queryRunner.query('CREATE INDEX `IDX_dd0918407944553611bb3eb3dd` ON `user_credentials` (`user_id`)');
        await queryRunner.query('CREATE INDEX `IDX_2081b465971c6e81d5447e0f65` ON `log_drops` (`theme_id`)');
        await queryRunner.query('CREATE INDEX `IDX_cc926133c401ae5e4c6cb943ee` ON `log_drops` (`user_id`)');
        await queryRunner.query('CREATE INDEX `IDX_7b72c0e6f5438539635fa2706d` ON `log_drops` (`game_id`)');
        await queryRunner.query('CREATE INDEX `IDX_200c5368f75e3f5fab815d2ba2` ON `themes` (`game_id`)');
        await queryRunner.query('CREATE INDEX `IDX_5d02077d4941019273995220b5` ON `song_clear_cards` (`theme_id`)');
        await queryRunner.query('CREATE INDEX `IDX_8fcb2c96a7b43862c2a1a19c28` ON `log_diamonds_ads` (`date`)');
        await queryRunner.query('CREATE INDEX `IDX_994987d0bdbd132c351dc863a6` ON `log_diamonds_ads` (`user_id`)');
        await queryRunner.query('CREATE INDEX `IDX_9402b99a15239b95309864535f` ON `log_diamonds_ads` (`game_id`)');
        await queryRunner.query('CREATE INDEX `IDX_80a98de140c38f1ed48b486570` ON `log_diamonds` (`user_id`)');
        await queryRunner.query('CREATE INDEX `IDX_58adef9aedebd662b88506583f` ON `log_diamonds` (`game_id`)');
        await queryRunner.query('CREATE INDEX `IDX_c619094b8afd1e48d28b6ee9f7` ON `log_credits` (`user_id`)');
        await queryRunner.query('CREATE INDEX `IDX_e0a817b68f55d95f6721267439` ON `log_credits` (`game_id`)');
        await queryRunner.query('CREATE UNIQUE INDEX `guid` ON `log_credits` (`guid`)');
        await queryRunner.query('CREATE INDEX `IDX_c8d12ea5178e0709deb03433d8` ON `song_beatmaps` (`song_id`)');
        await queryRunner.query('CREATE UNIQUE INDEX `IDX_83862467ad0a3afd66f49af374` ON `song_beatmaps` (`guid`)');
        await queryRunner.query('ALTER TABLE `zz__archive_song_world_records` ADD CONSTRAINT `FK_a2f2ebae5c9fcd5f2e6aac104ee` FOREIGN KEY (`gameId`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `users_logins` ADD CONSTRAINT `FK_9afce9c631e9dd84f6f4c9b0bc9` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `artists` ADD CONSTRAINT `FK_2e2fda1dec4c9bc16704e9ff772` FOREIGN KEY (`gameId`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `song_beatmaps` ADD CONSTRAINT `FK_c8d12ea5178e0709deb03433d82` FOREIGN KEY (`song_id`) REFERENCES `songs`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `league_tracker` ADD CONSTRAINT `FK_e0b3f9fcf35ff316a213c23d986` FOREIGN KEY (`divisionId`) REFERENCES `divisions`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
        await queryRunner.query('ALTER TABLE `league_tracker` ADD CONSTRAINT `FK_900818981d9eb49fd11fd70287c` FOREIGN KEY (`gameId`) REFERENCES `superstar_games`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT');
    }

}
